const lang = {
  en: {
    search: "search",
    gptSearchPlaceholders: [
      "Surprise me like my exam results did...",
      "Which movie will give me an existential crisis today?",
      "Looking for something better than my last situationship.",
      "Got 99 problems, but finding a movie ain’t one.",
      "Make me laugh so hard I forget adulthood exists.",
      "Need drama? I’ve got popcorn and no shame.",
      "Which film will destroy me emotionally (in a good way)?",
      "What's a show I can pretend I 'just discovered'?",
      "Help me find something bingeable before responsibilities kick in.",
      "I’m not crying, it’s just GPT’s recommendations again.",
      "Give me something so good, I cancel plans for it.",
      "GPT, hit me with a masterpiece — no pressure.",
      "Recommend something that says 'I have taste.'",
      "Pick something that ruins me, but I thank you later.",
      "Which title screams 'main character energy'?",
      "Ask GPT to recommend a hidden gem...",
      "Which mind-blowing plot twist should I watch tonight?",
      "Find your next binge-worthy obsession...",
      "Which movie matches my mood today?",
      "Suggest a thriller with a genius villain...",
      "Which show will ruin my sleep schedule next?",
      "What should I watch if I loved Stranger Things?",
      "Movie night but make it legendary…",
      "Got questions? GPT’s got better answers.",
      "Let the GPT magic begin…",
      "Something that makes me believe in love again (kinda).",
      "I want butterflies, but like… safe ones, not drama.",
      "Rom-com where I don’t end up single at the end pls?",
      "Give me love, betrayal, and a playlist-worthy kiss.",
      "I need a fictional couple to ruin real love for me.",
      "Any movie where the bar is literally in hell but he still clears it?",
      "Hopeless romantic, but make it toxic (just a lil).",
      "A slow burn so slow I die before they kiss.",
      "Enemies to lovers or nothing 😤",
      "Looking for: a fake dating scenario with real feels.",
      "Scare me so I forget real life fr 90 mins.",
      "Movie where the ghost has more personality than my ex.",
      "Jump scares? Sure. Existential dread? Bonus.",
      "Something spooky, but not like 'student loans' spooky.",
      "Give me a horror movie where I root for the killer.",
      "I want to scream, but like in a fun way.",
      "Haunted house but with good interior design.",
      "Anything where I yell 'WHY would you go in there?!'",
      "Need something that’s giving main character vibes 💅",
      "Plot twist: I was the ghost all along 👻",
      "Possession movies that feel emotionally relatable.",
    ],
  },
  hi: {
    search: "खोजें",
    gptSearchPlaceholders: [
      "दिल टूट चुका है, अब कुछ healing romance दो!",
      "कुछ ऐसा romantic जो पुराने crush की याद दिला दे...",
      "मोहब्बत वाली फिल्म, लेकिन extra cheesy हो!",
      "कुछ ऐसा डरावना दिखाओ कि लाइट्स ऑन करके सोना पड़े!",
      "डर ऐसा हो कि दोस्त भी हाथ पकड़ ले!",
      "रात को नींद ना आए, ऐसा कुछ spooky बताओ...",
      "कुछ ऐसा दो जो एक बार में ही 'add to favs' हो जाए!",
      "थोड़ा dark, थोड़ा deep – total Gen Z feels चाहिए!",
      "ऐसी मूवी दो जो Insta bio बना दूं!",
      "बोर हो रहा हूं, दिमाग घुमा दो अब...",
      "कोई ऐसी सीरीज़ बताओ, जिससे crush भी impress हो जाए 😎",
      "GPT, मेरी स्क्रीन टाइम worth बना दो यार!",
      "ऐसा कुछ सुझाओ कि पूरा घर binge करे...",
      "कुछ ऐसा हो कि मम्मी भी कहे, 'अच्छा है!'",
      "GPT भैया, दिल को छू जाए कुछ...",
      "कोई सीरीज़ जो इतनी अच्छी हो कि मैं खाना भूल जाऊं!",
      "इतना सस्पेंस दो कि नींद उड़ जाए!",
      "कोई ऐसी फिल्म बताओ, जिसे देखकर पड़ोसी भी पूछे – नाम क्या था?",
      "ऐसी वेब सीरीज़ चाहिए जो दिमाग हिला दे और दिल छू जाए!",
      "कुछ ऐसा दिखाओ जो बॉस के ताने भूल जाऊं!",
      "मन करे रोने का, लेकिन फिर भी दोबारा देखने का...",
      "प्यार, धोखा, बदला – सब एक साथ चाहिए!",
      "ऐसा शो चाहिए कि मोबाइल चार्जर से पहले मैं खत्म हो जाऊं!",
      "गर्मियों में AC से ज़्यादा ठंडा suspense दो!",
      "कोई ऐसी मूवी दो कि लगा दूं WhatsApp status पर!",
      "रिश्तेदारों से बचाने वाली सच्ची 'engaging' सीरीज़ बताओ!",
      "कोई तो content हो जो 'skip intro' का मन ही ना करे!",
    ],
  },
  es: {
    search: "buscar",
    gptSearchPlaceholders: [
      "Pídele a GPT una joya oculta para ver...",
      "¿Qué giro inesperado me va a dejar sin aliento?",
      "Encuentra tu próxima obsesión para maratonear...",
      "¿Qué película va con mi estado de ánimo hoy?",
      "Sugiere un thriller con un villano brillante...",
      "¿Qué serie arruinará mi sueño esta semana?",
      "Si amé Stranger Things, ¿qué más puedo ver?",
      "Noche de películas, pero que sea épica...",
      "¿Tienes preguntas? GPT tiene mejores respuestas.",
      "Que comience la magia de GPT...",
    ],
  },
  ja: {
    search: "検索",
    gptSearchPlaceholders: [
      "GPTに隠れた名作をおすすめしてもらおう...",
      "今夜はどんな衝撃の展開を見るべき？",
      "次に夢中になるシリーズを探そう...",
      "今の気分にぴったりの映画は？",
      "天才悪役が出るスリラーを教えて！",
      "睡眠不足になりそうなドラマはどれ？",
      "Stranger Thingsが好きなら次は？",
      "映画ナイトを伝説にしよう！",
      "質問ある？GPTが答えてくれるよ。",
      "さあ、GPTマジックの始まりだ！",
    ],
  },
  ko: {
    search: "검색",
    gptSearchPlaceholders: [
      "GPT에게 숨겨진 명작 추천받기...",
      "오늘 밤, 충격 반전 영화 뭐 볼까?",
      "정주행할 다음 시리즈를 찾아봐요...",
      "오늘 기분에 맞는 영화는 뭘까?",
      "천재 악당이 나오는 스릴러 추천해줘!",
      "내 수면을 망칠 드라마는 뭘까?",
      "Stranger Things 좋아했다면 뭐 볼까?",
      "전설이 될 영화 밤 만들어보자!",
      "질문 있어? GPT가 다 알려줄게.",
      "GPT 마법을 시작해볼까요?",
    ],
  },
};

export default lang;
